### ISSUE TITLE
does modified luci 0.11 work?

### ISSUE THREAD

**Issue by ssundaresan** [projectbismark/bismark-openwrt-overlay#4]
Are your changes stable? If so create a new repo in projectbismark.
Also list out the modifications you've made.

**Comment by shahifaqeer** [comment]
Backfire + luci 0.11 do not work correctly due to dependencies on some libraries (ubox, ubus) which have had major changes going from backfire to attitude.
The only solution I saw is to upgrade to attitude completely which works correctly with luci-0.11.
I modified luci-0.11 to add bismark-experiments and bismark-passive. It is stable with attitude. Will add it to projectbismark.

**Comment by ssundaresan** [comment]
Did you modify luci for your own experiments?

**Comment by shahifaqeer** [comment]
Not yet. My github/luci-0.11 repo is modified only to work with bismark lancre.
For my own experiments I'm currently installing luci-json and luci-rpc packages which I compile separately, and ssh a separate file into the router later.
github/luci-0.11 might have my bismark.lua file for my experiments, which isn't a part of the makefile (so it doesn't really compile). I'll delete this modification and you can basically clone my repo into luci-bismark directly to work with lancre then.

**Comment by shahifaqeer** [comment]
basically I am deleting luci-0.11/modules/fathom_rpc folder now (which I forgot to remove earlier). Thanks for reminding me about this.
